### ISSUE TITLE
Disable bold editor text

### ISSUE THREAD

**Issue by jonkri** [igolskyi/vscode-zenburn-plus-theme#1]
Hi, and thanks for a great theme!

Is there a way to have all editor text be displayed without bold (like with `font-weight: normal` or something)?

Thanks!

**Comment by igolskyi** [comment]
Hi @jonkri . Glad you liked it. So of course, wait for the next update.

**Comment by jonkri** [comment]
Hi, @igolskyi! Thank you very much! :slightly_smiling_face:

**Comment by igolskyi** [comment]
@jonkri, I just added a 'no bold' version of the theme and updated the repository on Github. But is a problem with access to the Microsoft Marketplace account, I wrote to them about it. Therefore, the topic in the marketplace is still not updated. As soon as the problem is solved, I will update the theme.
For now, if you know where the theme files are, you can copy the file code [zenburn-no-bold.json](https://github.com/igolskyi/vscode-zenburn-plus-theme/blob/master/themes/zenburn-no-bold.json) and temporarily replace it yourself in the file `.vscode/extensions/igolskyi.vscode-zenburn-plus-theme-0.3.0/themes/zenburn.json`.
The path may be different depending on your system.

**Comment by igolskyi** [comment]
@jonkri you can update theme to v 0.3.1. And select Zenburn+ Dark Theme(no bold)
![image](https://user-images.githubusercontent.com/22115961/122573824-ac840f00-d057-11eb-95fd-ea0492ef27c7.png)

**Comment by jonkri** [comment]
Thank you! :pray: 

(For some reason I can't see the update yet, even though I have restarted Code and tried __Extensions: Check for Extension Updates__ from the __Show All Commands__ menu. Perhaps it's because I'm using __Code - OSS__.)

**Comment by igolskyi** [comment]
@jonkri here is version 0.3.1https://marketplace.visualstudio.com/items?itemName=igolskyi.vscode-zenburn-plus-theme , can you try reinstall it?

**Comment by jonkri** [comment]
I uninstalled your theme, but when I searched for it in under __Extensions__ (or using <kbd>Ctrl + P</kbd> &gt; `ext install igolskyi.vscode-zenburn-plus-theme`) it couldn't be found. However, I can find other extensions (for example, the “Zenburn” theme shows up).

**Comment by igolskyi** [comment]
![image](https://user-images.githubusercontent.com/22115961/122687855-75615980-d221-11eb-9008-89a4d1cdf48a.png)
I don't know why you have a problem with this.
Probably through OSS.
Here is updated version https://marketplace.visualstudio.com/items?itemName=igolskyi.vscode-zenburn-plus-theme

![image](https://user-images.githubusercontent.com/22115961/122688032-7e065f80-d222-11eb-9dba-b0ac11649e70.png)

**Comment by jonkri** [comment]
Just a quick update:

I installed the update manually from the VSIX file found on [the download page](https://marketplace.visualstudio.com/items?itemName=igolskyi.vscode-zenburn-plus-theme) and it works beautifully.

Thanks again! :slightly_smiling_face:
